//! Egui UI helpers for editing texture generator configs.
//!
//! Provides reusable widgets for every texture config type so any application
//! with `bevy_egui` can embed texture parameter controls without duplicating
//! editor code.
//!
//! # Signature convention
//!
//! Every config editor has the form:
//! ```text
//! pub fn xxx_config_editor(ui: &mut egui::Ui, cfg: &mut XxxConfig, id: egui::Id) -> (bool, bool)
//! ```
//!
//! - `id` — used as the collapsing-header id salt; build with `egui::Id::new(x)`
//!   or derive a child ID via `parent.with("label")`.
//! - Returns `(writeback, regen)`:
//!   - `writeback` — any widget changed (including mid-drag). Write the config
//!     back to your resource to prevent slider snap-back.
//!   - `regen` — a value was *committed*: drag ended or a non-drag widget changed.
//!     Only regenerate the texture when this is `true`.
//!
//! # Where the panels come from
//!
//! Every editor function is generated by `impl_config_editor!` as a callback
//! over [`symbios_texture::for_each_texture_field!`] — the core crate's
//! per-field registry, which is also where the `Genotype` impls and the
//! record-boundary envelope clamp come from. This module owns the *widget
//! vocabulary* (which control a field kind gets, and its debouncing) and
//! nothing about any individual field: a slider's range is the field's
//! envelope, authored once beside the range mutation and an application's
//! sanitiser use.
//!
//! Two columns of a registry row belong to this module. `label` is the ident
//! `none` on the six fields that are evolvable but not editable, which is how
//! they stay out of a panel. And an optional `layout { … }` list gives the
//! *display* order where it differs from the table's order — the table is in
//! mutation-draw order, which is behaviour rather than presentation — and is
//! the only place `separator()` and `text("…")` may appear.
//!
//! Enabled via the `egui` Cargo feature.

use bevy_egui::egui;
use symbios_texture::for_each_texture_field;

// ---------------------------------------------------------------------------
// Declarative macro for config editors
// ---------------------------------------------------------------------------

/// Generates a public editor function for every config in the per-field
/// registry.
///
/// # Widget kinds
///
/// The mapping from a registry row's kind to a widget is total — there is no
/// debounced integer field and no instant slider — so a row carries no widget
/// column of its own.
///
/// | Row kind | Widget | Commit semantics |
/// |----------|--------|------------------|
/// | `f64`, `f32` | Slider over the field's envelope | debounced: writeback on change, regen on commit |
/// | `f64_round` | The same, stepping by 1 | debounced |
/// | `usize` | Integer slider | immediate: both on change |
/// | `seed` | Drag value | immediate |
/// | `color3` | Colour picker | immediate |
/// | `bool` | Checkbox | immediate |
/// | `enum_pick` | Row of selectable labels | immediate |
/// | `nested` | The sub-config's own editor, salted | merged |
///
/// A row whose label is `none` draws nothing; `separator()` and `text("…")`
/// come from the `layout` list, never from a row. The `explore` clause and a
/// `fixup` name are the core crate's business and are matched and discarded.
macro_rules! impl_config_editor {
    // Callback entry: one editor function per registry entry.
    (
        $(
            $Config:ty, $header:literal, $editor:ident
            $(, fixup $fixup:ident )?
            { $(
                $kind:ident ( $field:ident $($rest:tt)* )
                $( explore ( $xlo:expr, $xhi:expr ) )?
            ),+ $(,)? }
            $( layout { $($layout:tt)* } )?
        ),+ $(,)?
    ) => {
        $(
            #[doc = concat!(
                "Renders every editable [`", stringify!($Config),
                "`] parameter inside a collapsing header."
            )]
            pub fn $editor(
                ui: &mut egui::Ui,
                cfg: &mut $Config,
                id: egui::Id,
            ) -> (bool, bool) {
                let mut wb = false;
                let mut regen = false;
                egui::CollapsingHeader::new($header)
                    .id_salt(id)
                    .show(ui, |ui| {
                        // `ui` here is the closure's, shadowing the argument;
                        // both are written in this template, so passing it on
                        // keeps the widgets inside the header.
                        impl_config_editor!(@body ui, cfg, id, wb, regen,
                            rows { $( $kind ($field $($rest)*) ),+ }
                            $( layout { $($layout)* } )?
                        );
                    });
                (wb, regen)
            }
        )+
    };

    // --- panel body ---------------------------------------------------------

    // No layout list: the panel lists its fields in table order, and a row
    // with no label expands to nothing.
    (@body $ui:ident, $cfg:ident, $id:ident, $wb:ident, $regen:ident,
     rows { $( $kind:ident ( $field:ident $($rest:tt)* ) ),+ }) => {
        $( impl_config_editor!(
            @widget $ui, $cfg, $id, $wb, $regen, $kind ($field $($rest)*)
        ); )+
    };

    // With one: each row becomes an arm of a local `widget!`, and the list
    // says what to draw and in what order. The arms carry no `$` of their
    // own, which is what makes a macro definable from inside a macro.
    (@body $ui:ident, $cfg:ident, $id:ident, $wb:ident, $regen:ident,
     rows { $( $kind:ident ( $field:ident $($rest:tt)* ) ),+ }
     layout { $($step:tt)* }) => {
        macro_rules! widget {
            $( ( $field ) => {
                impl_config_editor!(
                    @widget $ui, $cfg, $id, $wb, $regen, $kind ($field $($rest)*)
                );
            }; )+
        }
        impl_config_editor!(@steps widget, $ui, $($step)*);
    };

    // --- layout walker ------------------------------------------------------

    (@steps $w:ident, $ui:ident,) => {};
    (@steps $w:ident, $ui:ident, , $($rest:tt)*) => {
        impl_config_editor!(@steps $w, $ui, $($rest)*);
    };
    (@steps $w:ident, $ui:ident, separator() $($rest:tt)*) => {
        $ui.separator();
        impl_config_editor!(@steps $w, $ui, $($rest)*);
    };
    (@steps $w:ident, $ui:ident, text($text:literal) $($rest:tt)*) => {
        $ui.label($text);
        impl_config_editor!(@steps $w, $ui, $($rest)*);
    };
    (@steps $w:ident, $ui:ident, $field:ident $($rest:tt)*) => {
        $w!($field);
        impl_config_editor!(@steps $w, $ui, $($rest)*);
    };

    // --- widget arms --------------------------------------------------------

    // A `none` label means evolvable but not editable: no widget at all.
    (@widget $ui:ident, $cfg:ident, $id:ident, $wb:ident, $regen:ident,
     $kind:ident ($field:ident, none $($rest:tt)*)) => {};

    (@widget $ui:ident, $cfg:ident, $id:ident, $wb:ident, $regen:ident,
     seed ($field:ident, $label:literal)) => {
        u32_instant($ui, &mut $cfg.$field, $label, &mut $wb, &mut $regen);
    };
    (@widget $ui:ident, $cfg:ident, $id:ident, $wb:ident, $regen:ident,
     f64 ($field:ident, $label:literal, $min:expr, $max:expr, $half:expr)) => {
        slider_debounced(
            $ui,
            egui::Slider::new(&mut $cfg.$field, $min..=$max).text($label),
            &mut $wb,
            &mut $regen,
        );
    };
    (@widget $ui:ident, $cfg:ident, $id:ident, $wb:ident, $regen:ident,
     f32 ($field:ident, $label:literal, $min:expr, $max:expr, $half:expr)) => {
        slider_debounced(
            $ui,
            egui::Slider::new(&mut $cfg.$field, $min..=$max).text($label),
            &mut $wb,
            &mut $regen,
        );
    };
    // A field the search rounds is a count, so its slider steps like one.
    (@widget $ui:ident, $cfg:ident, $id:ident, $wb:ident, $regen:ident,
     f64_round ($field:ident, $label:literal, $min:expr, $max:expr, $half:expr)) => {
        slider_debounced(
            $ui,
            egui::Slider::new(&mut $cfg.$field, $min..=$max)
                .step_by(1.0)
                .text($label),
            &mut $wb,
            &mut $regen,
        );
    };
    (@widget $ui:ident, $cfg:ident, $id:ident, $wb:ident, $regen:ident,
     usize ($field:ident, $label:literal, $min:expr, $max:expr)) => {
        usize_instant($ui, &mut $cfg.$field, $min..=$max, $label, &mut $wb, &mut $regen);
    };
    (@widget $ui:ident, $cfg:ident, $id:ident, $wb:ident, $regen:ident,
     color3 ($field:ident, $label:literal, $half:expr)) => {
        color_instant($ui, $label, &mut $cfg.$field, &mut $wb, &mut $regen);
    };
    (@widget $ui:ident, $cfg:ident, $id:ident, $wb:ident, $regen:ident,
     bool ($field:ident, $label:literal)) => {
        bool_instant($ui, &mut $cfg.$field, $label, &mut $wb, &mut $regen);
    };
    (@widget $ui:ident, $cfg:ident, $id:ident, $wb:ident, $regen:ident,
     enum_pick ($field:ident, $label:literal, [ $(($variant:expr, $btn:literal)),+ ])) => {
        $ui.horizontal(|ui| {
            ui.label($label);
            $(
                let selected = $cfg.$field == $variant;
                if ui.selectable_label(selected, $btn).clicked() && !selected {
                    $cfg.$field = $variant;
                    $wb = true;
                    $regen = true;
                }
            )+
        });
    };
    (@widget $ui:ident, $cfg:ident, $id:ident, $wb:ident, $regen:ident,
     nested ($field:ident, $sub:ty, $sub_editor:ident, $salt:literal)) => {
        let (sub_wb, sub_regen) = $sub_editor($ui, &mut $cfg.$field, $id.with($salt));
        $wb |= sub_wb;
        $regen |= sub_regen;
    };
}

// ---------------------------------------------------------------------------
// Editor implementations — one per entry of the per-field registry
// ---------------------------------------------------------------------------

for_each_texture_field!(impl_config_editor);

/// Renders the editor for whichever generator `cfg` currently wraps.
///
/// Returns the same `(changed, regen)` pair as the per-config editors.
/// [`TextureConfig::None`](crate::material::TextureConfig::None) renders
/// nothing.  The match is exhaustive, so a registry row without an editor
/// fails compilation here — keeping the egui surface in sync with the
/// generator roster.
pub fn texture_config_editor(
    ui: &mut egui::Ui,
    cfg: &mut crate::material::TextureConfig,
    id: egui::Id,
) -> (bool, bool) {
    use crate::material::TextureConfig as TC;
    match cfg {
        TC::None => (false, false),
        TC::Leaf(c) => leaf_config_editor(ui, c, id),
        TC::Twig(c) => twig_config_editor(ui, c, id),
        TC::Bark(c) => bark_config_editor(ui, c, id),
        TC::Window(c) => window_config_editor(ui, c, id),
        TC::StainedGlass(c) => stained_glass_config_editor(ui, c, id),
        TC::IronGrille(c) => iron_grille_config_editor(ui, c, id),
        TC::Ground(c) => ground_config_editor(ui, c, id),
        TC::Rock(c) => rock_config_editor(ui, c, id),
        TC::Brick(c) => brick_config_editor(ui, c, id),
        TC::Plank(c) => plank_config_editor(ui, c, id),
        TC::Shingle(c) => shingle_config_editor(ui, c, id),
        TC::Stucco(c) => stucco_config_editor(ui, c, id),
        TC::Concrete(c) => concrete_config_editor(ui, c, id),
        TC::Metal(c) => metal_config_editor(ui, c, id),
        TC::Pavers(c) => pavers_config_editor(ui, c, id),
        TC::Ashlar(c) => ashlar_config_editor(ui, c, id),
        TC::Cobblestone(c) => cobblestone_config_editor(ui, c, id),
        TC::Thatch(c) => thatch_config_editor(ui, c, id),
        TC::Marble(c) => marble_config_editor(ui, c, id),
        TC::Corrugated(c) => corrugated_config_editor(ui, c, id),
        TC::Asphalt(c) => asphalt_config_editor(ui, c, id),
        TC::Wainscoting(c) => wainscoting_config_editor(ui, c, id),
        TC::Encaustic(c) => encaustic_config_editor(ui, c, id),
        TC::SoftDisc(c) => soft_disc_config_editor(ui, c, id),
        TC::Spark(c) => spark_config_editor(ui, c, id),
        TC::Snowflake(c) => snowflake_config_editor(ui, c, id),
        TC::Puff(c) => puff_config_editor(ui, c, id),
        TC::Ring(c) => ring_config_editor(ui, c, id),
        TC::Petal(c) => petal_config_editor(ui, c, id),
        TC::Shard(c) => shard_config_editor(ui, c, id),
        TC::LeafSprite(c) => leaf_sprite_config_editor(ui, c, id),
        TC::Flame(c) => flame_config_editor(ui, c, id),
        TC::Flower(c) => flower_config_editor(ui, c, id),
        TC::GrassTuft(c) => grass_config_editor(ui, c, id),
        TC::Frond(c) => frond_config_editor(ui, c, id),
        TC::CactusSkin(c) => cactus_config_editor(ui, c, id),
        TC::Moss(c) => moss_config_editor(ui, c, id),
        TC::Lichen(c) => lichen_config_editor(ui, c, id),
        TC::Reed(c) => reed_config_editor(ui, c, id),
        TC::Needle(c) => needle_config_editor(ui, c, id),
        TC::Broadleaf(c) => broadleaf_config_editor(ui, c, id),
        TC::Fabric(c) => fabric_config_editor(ui, c, id),
        TC::Sand(c) => sand_config_editor(ui, c, id),
        TC::Snow(c) => snow_config_editor(ui, c, id),
        TC::Ice(c) => ice_config_editor(ui, c, id),
        TC::Lava(c) => lava_config_editor(ui, c, id),
        TC::ChainLink(c) => chain_link_config_editor(ui, c, id),
        TC::LogEnd(c) => log_end_config_editor(ui, c, id),
        TC::CrackedEarth(c) => cracked_earth_config_editor(ui, c, id),
        TC::Gravel(c) => gravel_config_editor(ui, c, id),
        TC::ForestFloor(c) => forest_floor_config_editor(ui, c, id),
        TC::Enamel(c) => enamel_config_editor(ui, c, id),
        TC::Obsidian(c) => obsidian_config_editor(ui, c, id),
        TC::Chitin(c) => chitin_config_editor(ui, c, id),
        TC::SolarPanel(c) => solar_panel_config_editor(ui, c, id),
        TC::Parquet(c) => parquet_config_editor(ui, c, id),
        TC::Truchet(c) => truchet_config_editor(ui, c, id),
    }
}

/// Adds a slider with drag-aware debouncing.
///
/// - `writeback` accumulates on any `changed()` (including mid-drag) so the
///   caller can write the value back and prevent visual snap-back.
/// - `regen` accumulates only on `drag_stopped()` or a non-drag change, avoiding
///   unnecessary texture regeneration during continuous slider drags.
pub fn slider_debounced(
    ui: &mut egui::Ui,
    slider: impl egui::Widget,
    writeback: &mut bool,
    regen: &mut bool,
) {
    let r = ui.add(slider);
    *writeback |= r.changed();
    *regen |= r.drag_stopped() || (r.changed() && !r.dragged());
}

/// Horizontal labeled slider for `f32` values. Returns `true` on any change.
pub fn f32_slider(
    ui: &mut egui::Ui,
    val: &mut f32,
    label: &str,
    range: std::ops::RangeInclusive<f32>,
) -> bool {
    ui.horizontal(|ui| {
        ui.label(label);
        ui.add(egui::Slider::new(val, range)).changed()
    })
    .inner
}

/// Horizontal labeled slider for `f64` values. Returns `true` on any change.
pub fn f64_slider(
    ui: &mut egui::Ui,
    val: &mut f64,
    label: &str,
    range: std::ops::RangeInclusive<f64>,
) -> bool {
    ui.horizontal(|ui| {
        ui.label(label);
        ui.add(egui::Slider::new(val, range)).changed()
    })
    .inner
}

/// Horizontal labeled slider for `usize` values. Returns `true` on any change.
pub fn usize_slider(
    ui: &mut egui::Ui,
    val: &mut usize,
    label: &str,
    range: std::ops::RangeInclusive<usize>,
) -> bool {
    ui.horizontal(|ui| {
        ui.label(label);
        ui.add(egui::Slider::new(val, range)).changed()
    })
    .inner
}

/// Horizontal labeled drag value for `u32`. Returns `true` on any change.
pub fn u32_drag(ui: &mut egui::Ui, val: &mut u32, label: &str) -> bool {
    ui.horizontal(|ui| {
        ui.label(label);
        ui.add(egui::DragValue::new(val).speed(1.0)).changed()
    })
    .inner
}

// ---------------------------------------------------------------------------
// Private inline helpers used only within this module
// ---------------------------------------------------------------------------

/// Color picker that immediately sets both writeback and regen flags.
fn color_instant(
    ui: &mut egui::Ui,
    label: &str,
    color: &mut [f32; 3],
    wb: &mut bool,
    regen: &mut bool,
) {
    ui.horizontal(|ui| {
        ui.label(label);
        let r = ui.color_edit_button_rgb(color);
        *wb |= r.changed();
        *regen |= r.changed();
    });
}

/// Checkbox that immediately sets both writeback and regen flags.
fn bool_instant(ui: &mut egui::Ui, val: &mut bool, label: &str, wb: &mut bool, regen: &mut bool) {
    let r = ui.checkbox(val, label);
    *wb |= r.changed();
    *regen |= r.changed();
}

/// Integer usize slider that immediately sets both flags (integer steps are cheap to regen).
fn usize_instant(
    ui: &mut egui::Ui,
    val: &mut usize,
    range: std::ops::RangeInclusive<usize>,
    label: &str,
    wb: &mut bool,
    regen: &mut bool,
) {
    let r = ui.add(egui::Slider::new(val, range).text(label));
    *wb |= r.changed();
    *regen |= r.changed();
}

/// Integer u32 drag that immediately sets both flags.
fn u32_instant(ui: &mut egui::Ui, val: &mut u32, label: &str, wb: &mut bool, regen: &mut bool) {
    ui.horizontal(|ui| {
        ui.label(label);
        let r = ui.add(egui::DragValue::new(val).speed(1.0));
        *wb |= r.changed();
        *regen |= r.changed();
    });
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use symbios_texture::for_each_texture_field;

    /// A `layout` list decides what a panel draws, so a field missing from one
    /// disappears from the UI without any compiler complaint — the row still
    /// exists, it is simply never invoked. This compares the two lists by name
    /// for every config that has a layout, so an omission, a duplicate or a
    /// typo fails here instead of silently losing a control.
    #[test]
    fn every_layout_lists_every_editable_field() {
        let mut checked = 0usize;

        macro_rules! check_layouts {
            (
                $(
                    $Config:ty, $header:literal, $editor:ident
                    $(, fixup $fixup:ident )?
                    { $(
                        $kind:ident ( $field:ident $($rest:tt)* )
                        $( explore ( $xlo:expr, $xhi:expr ) )?
                    ),+ $(,)? }
                    $( layout { $($step:tt)* } )?
                ),+ $(,)?
            ) => {
                $( check_layouts!(
                    @one $header, [ $( $kind ($field $($rest)*) ),+ ]
                    $( layout { $($step)* } )?
                ); )+
            };

            (@one $header:literal, [ $( $kind:ident ( $field:ident $($rest:tt)* ) ),+ ]
             layout { $($step:tt)* }) => {{
                // A row with no label is a field that is deliberately not
                // editable, and contributes nothing to a panel.
                let mut rows: Vec<&str> =
                    [ $( check_layouts!(@row $kind ($field $($rest)*)) ),+ ]
                        .into_iter()
                        .flatten()
                        .collect();
                let mut steps: Vec<&str> =
                    Vec::from(check_layouts!(@steps [] $($step)*));
                rows.sort_unstable();
                steps.sort_unstable();
                assert!(!rows.is_empty(), "the {} panel has no fields", $header);
                assert_eq!(
                    rows, steps,
                    "the {} panel's layout and its editable fields disagree",
                    $header
                );
                checked += 1;
            }};
            // No layout list: the panel draws its fields in table order, so
            // there is nothing that can fall out of step.
            (@one $header:literal, [ $($rows:tt)* ]) => {};

            (@row $kind:ident ($field:ident, none $($rest:tt)*)) => { None };
            (@row $kind:ident ($field:ident $($rest:tt)*)) => { Some(stringify!($field)) };

            // Walk the layout, collecting field names and dropping the two
            // presentation-only steps.
            (@steps [$($name:expr,)*]) => { [$($name,)*] };
            (@steps [$($name:expr,)*] , $($rest:tt)*) => {
                check_layouts!(@steps [$($name,)*] $($rest)*)
            };
            (@steps [$($name:expr,)*] separator() $($rest:tt)*) => {
                check_layouts!(@steps [$($name,)*] $($rest)*)
            };
            (@steps [$($name:expr,)*] text($text:literal) $($rest:tt)*) => {
                check_layouts!(@steps [$($name,)*] $($rest)*)
            };
            (@steps [$($name:expr,)*] $field:ident $($rest:tt)*) => {
                check_layouts!(@steps [$($name,)* stringify!($field),] $($rest)*)
            };
        }

        for_each_texture_field!(check_layouts);

        assert_eq!(
            checked, 7,
            "seven configs list their fields in an order that differs from the \
             table's: Bark, Leaf, Twig, Metal, Gravel, Flower, LeafSprite. If \
             this count drops, a layout list was removed and that panel \
             silently reordered."
        );
    }
}
